apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-example-deploy-only
spec:
  environments:
  - name: demo
    build:
      from: master
  components:
  - name: helloworld
    image: docker.pkg.github.com/equinor/radix-example-deploy-only/helloworld:{imageTagName}
    # Because the tag will not change
    alwaysPullImageOnDeploy: true
    # ---
    ports:
    - name: http
      port: 8080
    public: true
    environmentConfig:
    - environment: demo
      imageTagName: latest
      horizontalScaling:
        minReplicas: 1
        maxReplicas: 3
      monitoring: false
      resources:
        requests:
          memory: 10M
          cpu: 5m
        limits:
          memory: 20M
          cpu: 50m
  privateImageHubs:
    docker.pkg.github.com:
      username: JoakimHagen
      email: johagen@equinor.com
