name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    env:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.K8S_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v1
      - name: Set image tag
        run: |
          echo ::set-env name=IMAGE_TAG::latest
      - name: Build
        run: |
          docker build -t docker.pkg.github.com/equinor/radix-example-arm-template/api:latest ./todoapi/
      - name: Push the image to GPR
        run: |
          echo ${{ secrets.PRIVATE_TOKEN }} | docker login docker.pkg.github.com -u JoakimHagen --password-stdin
          docker push docker.pkg.github.com/equinor/radix-example-deploy-only/helloworld:latest
      - name: Deploy to Radix
        uses: equinor/radix-github-actions@master
        with:
          args: >
            create job deploy
            --from-config
            --context development
            --environment demo
            -f
      # restart is required to update running components from static image-tags
      - name: Restart on Radix to update latest image
        uses: equinor/radix-github-actions@master
        with:
          # environment and component name are hardcoded for the latest deployment
          args: >
            restart component
            --from-config
            --context development
            --environment demo
            --component helloworld
